name: Deploy Server to Elastic Beanstalk

on:
  push:
    branches:
      - vutlhari-feature/oauth-JWT

jobs:
  build:
    name: killerbeans-server
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'
          java-package: jdk
          architecture: x64
          check-latest: false
          server-id: github
          server-username: ${{ github.actor }}
          server-password: ${{ github.token }}
          overwrite-settings: true
          job-status: success
      
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build with Maven
        id: build
        working-directory: server
        run: mvn -B package --file pom.xml

      - name: Upload JAR
        uses: actions/upload-artifact@v3
        with:
          name: killer-beans-server
          path: server/target/killer-beans-server.jar

  deploy:
    runs-on: ubuntu-latest

    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download JAR
        uses: actions/download-artifact@v3
        with:
          name: killer-beans-server
      
      - name: List target directory contents
        run: sudo ls ${{ github.workspace }}

      - name: Deploy Server to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: killer-beans
          environment_name: Killer-beans-env
          region: 'eu-west-1'
          version_label: v${{ github.run_number }}
          deployment_package: ${{ github.workspace }}/killer-beans-server.jar
