name: Deploy Server to Elastic Beanstalk

on:
  push:
    branches:
      - vutlhari-feature/oauth-JWT

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'  # Optional: Choose a different distribution if needed
          java-package: jdk
          architecture: x64
          check-latest: false  # Disables automatic update check
          server-id: github
          server-username: ${{ github.actor }}
          server-password: ${{ github.token }}
          overwrite-settings: true
          job-status: success

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Clean target directory (Optional)
        run: rm -rf server/target

      - name: Build with Maven
        id: build
        working-directory: server
        run: mvn -B package --file pom.xml || exit 1  # Exit 1 on build failure
        outputs:
          jarFileName: target/*.jar  # Capture JAR file path

      - name: List target directory contents (Optional)
        run: ls server/target

  deploy:
    runs-on: ubuntu-latest
    needs: build  # This job depends on the successful completion of 'build' job

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy Server to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: killer-beans
          environment_name: Killer-beans-env
          region: 'eu-west-1'
          version_label: v${{ github.run_number }}
          source_bundle: ${{ steps.build.outputs.jarFileName }}  # Reference JAR from build output
