name: Deploy Server to Elastic Beanstalk

on:
  push:
    branches:
      - vutlhari-feature/oauth-JWT

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21' 

      - name: Build Server with Maven
        run: |
          cd server
          mvn -B package --file pom.xml

      - name: Deploy Server to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v15
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: 'killer-beans'
          environment_name: 'Killer-beans-env'
          region: 'eu-west-1'
          version_label: 'v${{ github.run_number }}'
          source_bundle: 'server/target/server-0.0.1-SNAPSHOT.jar'
