name: Database Migration Tests with Flyway

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/database/flyway/scripts/**'

  workflow_dispatch:

jobs:
  test-migrations:
    name: Test flyway migration scripts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Update
        run: sudo apt update
      - name: install snapd
        run: sudo apt install snapd
      - name: Install Flyway 
        run: sudo snap install flyway
      - name: Run flyway
        run: flyway migrate -password=${{ secrets.DB_PASSWORD }} -configFile=flyway.conf
