name: Build and Deploy

on:
  push:
    branches:
      # - main  # Adjust this according to your branch naming convention
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Navigate to Spring app directory
      run: cd server

    - name: List things
      run: ls

    - name: Build with Maven
      run: mvn -B package --file pom.xml

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to EC2
      run: |
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa target/server-0.0.1-SNAPSHOT.jar ec2-user@54.75.19.219:home/ec2-user


