name: Trigger Release Workflow

on:
  workflow_dispatch:

jobs:
  trigger_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Trigger Release Workflow
        uses: actions/github-script@v6
        with:
          script: |
            github.actions.getWorkflowRuns({ workflow_id: 'release.yml' }).then(workflowRuns => {
              if (workflowRuns.total_count === 0) {
                github.actions.createWorkflowRun({ workflow_id: 'release.yml' })
              } else {
                console.log("Release workflow already running or recently completed.")
              }
            })
