name: Creating Executable file

on:
  push:
    branches:
      - vutlhari-feature/oauth-JWT

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'
          java-package: jdk
          architecture: x64
          check-latest: false

      - name: Build with Maven
        id: build
        working-directory: app
        run: mvn -B package --file pom.xml -Dmaven.test.skip=true

      - name: Upload JAR
        uses: actions/upload-artifact@v3
        with:
          name: killer-beans-client
          path: app/target/killer-beans-client.jar

  create-exe:
    runs-on: windows-latest  # Change to windows-latest runner
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download JAR
        uses: actions/download-artifact@v3
        with:
          name: killer-beans-client  

      - name: Download Launch4j executable
        run: |
          curl -o launch4j.exe https://elasticbeanstalk-eu-west-1-434468814231.s3.eu-west-1.amazonaws.com/launch4j-3.50-win32.exe

      - name: Set permissions for launch4j.exe
        run: chmod +x ${{ github.workspace }}/launch4j.exe

      - name: Create EXE
        run: ${{ github.workspace }}/launch4j.exe -config /launch4j.xml -cp ${{ github.workspace }}/killer-beans-client.jar -outfile ${{ github.workspace }}/killer-beans-client.exe
      

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: killer-beans-client-exe
          path: ${{ github.workspace }}/killer-beans-client.exe
      - name: list files
        run: ls ${{github.workspace}}



  create-release:
    runs-on: ubuntu-latest
    needs: create-exe
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Exe
        uses: actions/download-artifact@v3
        with:
          name: killer-beans-client
      - name: list files
        run: ls ${{ github.workspace }}

      - name: Create Release
        uses: ncipollo/release-action@v1.10.0
        with:
          tag: v${{ github.run_number }}
          name: killer-beans-${{ github.run_number }}
          body: "Automated release with .exe file"
          draft: false
          artifacts: ${{ github.workspace }}/killer-beans-client.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

